CQCL/pytket-qiskit

- pytket/extensions/qiskit/backends/ibm.py
reopened from https://github.com/CQCL/pytket-extensions/pull/473
> Defaults to False since no backend info available.

- README.md
moved over from https://github.com/CQCL/pytket-extensions/pull/466
please check if everything has been added correctly
> add def comp info for pytket-qiskit

- docs/intro.txt
Found some more broken links in the documentation. They should work now.
> fix broken links

- docs/changelog.rst
- pytket/extensions/qiskit/tket_backend.py
- pytket/extensions/qiskit/tket_job.py
- tests/mock_pytket_backend.py
- tests/qiskit_backend_test.py
This PR should fix #14 and #15
> Bugfix/fix bugs in TketBackend

- _metadata.py
- docs/changelog.rst
- pytket/extensions/qiskit/qiskit_convert.py
- setup.py
- tests/qiskit_convert_test.py
And bump pytket requirement to 1.9.0rc0.
> Handle `OpType.Phase` when converting to qiskit

- _metadata.py
- docs/changelog.rst
- pytket/extensions/qiskit/qiskit_convert.py
- tests/qiskit_convert_test.py
> Fix handling of parameter when converting PauliEvolutionGate to QubitPauliOperator

- docs/changelog.rst
- pytket/extensions/qiskit/backends/aer.py
- pytket/extensions/qiskit/qiskit_convert.py
- pytket/extensions/qiskit/result_convert.py
- tests/backend_test.py
- tests/qiskit_convert_test.py
> Fix (and simplify) handling of endianness and unit ordering

- docs/changelog.rst
- setup.py
> Feature/qiskit 0.41

- docs/changelog.rst
- pytket/extensions/qiskit/qiskit_convert.py
- tests/qiskit_convert_test.py
> Take account of control state for controlled gates in `qiskit_to_tk`

- docs/changelog.rst
- pytket/extensions/qiskit/backends/aer.py
- pytket/extensions/qiskit/qiskit_convert.py
- tests/qiskit_convert_test.py
> Fix conversion of qiskit `UnitaryGate` to pytket

- docs/changelog.rst
- pytket/extensions/qiskit/backends/aer.py
- pytket/extensions/qiskit/result_convert.py
- pytket/extensions/qiskit/tket_backend.py
- setup.py
> Update qiskit to 0.44

- pytket/extensions/qiskit/qiskit_convert.py
OK since we now require pytket >= 1.19.
> Clean up import.

- mypy.ini
- pytket/extensions/qiskit/__init__.py
- pytket/extensions/qiskit/backends/aer.py
- pytket/extensions/qiskit/backends/crosstalk_model.py
- pytket/extensions/qiskit/backends/ibm.py
- pytket/extensions/qiskit/backends/ibm_utils.py
- pytket/extensions/qiskit/backends/ibmq_emulator.py
- pytket/extensions/qiskit/qiskit_convert.py
- pytket/extensions/qiskit/result_convert.py
- pytket/extensions/qiskit/tket_backend.py
- pytket/extensions/qiskit/tket_job.py
- pytket/extensions/qiskit/tket_pass.py
- tests/backend_test.py
- tests/mock_pytket_backend.py
- tests/qiskit_backend_test.py
- tests/qiskit_convert_test.py
add warn for unused ignores flag, remove unused ignores, general clean-up
> mypy warn-unused-ignore

- tests/backend_test.py
- tests/conftest.py
- tests/qiskit_backend_test.py
- tests/qiskit_convert_test.py
Closes #152 .
Integration tests running here: https://github.com/CQCL/pytket-qiskit/actions/runs/6340224704
> Update integration tests to replace retired backends with current ones

- docs/changelog.rst
Adding the missing changelog entry for the change made in #203.
> Add missing changelog entry

- docs/changelog.rst
- setup.py
> Bump qiskit-ibm-runtime to 0.15

- docs/changelog.rst
- setup.py
update ibm runtime to 0.17.0 see https://github.com/CQCL/pytket-qiskit/issues/223
> update ibm runtime

- .github/workflows/build_and_test.yml
- .github/workflows/docs.yml
> update github actions

- .github/pull_request_template.md
- .github/workflows/build_and_test.yml
- .github/workflows/docs.yml
- .github/workflows/docs/conf.py
- .github/workflows/docs/requirements.txt
- .github/workflows/lint.yml
- _metadata.py
- docs/api.rst
- docs/changelog.rst
- pytket/extensions/qiskit/backends/crosstalk_model.py
- pytket/extensions/qiskit/backends/ibm.py
- setup.py
- tests/backend_test.py
- tests/conftest.py
- tests/mock_pytket_backend.py
- tests/qiskit_convert_test.py
> Release 0.47.0

- .github/workflows/docs/conf.py
- pytket/extensions/qiskit/__init__.py
- pytket/extensions/qiskit/backends/__init__.py
- pytket/extensions/qiskit/backends/aer.py
- pytket/extensions/qiskit/backends/crosstalk_model.py
- pytket/extensions/qiskit/backends/ibm.py
- pytket/extensions/qiskit/backends/ibmq_emulator.py
- pytket/extensions/qiskit/qiskit_convert.py
- pytket/extensions/qiskit/result_convert.py
- pytket/extensions/qiskit/tket_backend.py
- pytket/extensions/qiskit/tket_job.py
- pytket/extensions/qiskit/tket_pass.py
- setup.py
- tests/backend_test.py
- tests/conftest.py
- tests/mock_pytket_backend.py
- tests/qiskit_backend_test.py
- tests/qiskit_convert_test.py
> update copyright 2024

- docs/changelog.rst
- pytket/extensions/qiskit/qiskit_convert.py
- tests/qiskit_backend_test.py
- tests/qiskit_convert_test.py
Fix https://github.com/CQCL/pytket-qiskit/issues/43 and https://github.com/CQCL/pytket-qiskit/issues/224
> fix issue with conditional and symbolic parameter in conversion

- tests/conftest.py
- tests/qiskit_backend_test.py
Changing the backed of the not working testcase to the simulator that is used.
Submitting a bug report to qiskit about the not working sampler. (see https://github.com/Qiskit/qiskit/issues/11939 )
Adding the submitted testcase to the expected failures.
https://github.com/CQCL/pytket-qiskit/issues/272
> mark not working testcase

- .github/workflows/build_and_test.yml
- _metadata.py
- docs/api.rst
- docs/changelog.rst
- docs/intro.txt
- pytket/extensions/qiskit/__init__.py
- pytket/extensions/qiskit/backends/__init__.py
- pytket/extensions/qiskit/backends/aer.py
- pytket/extensions/qiskit/backends/crosstalk_model.py
- pytket/extensions/qiskit/backends/ibm.py
- pytket/extensions/qiskit/backends/ibmq_emulator.py
- pytket/extensions/qiskit/backends/ibmq_local_emulator.py
- pytket/extensions/qiskit/qiskit_convert.py
- pytket/extensions/qiskit/tket_pass.py
- setup.py
- tests/backend_test.py
- tests/conftest.py
- tests/qiskit_backend_test.py
- tests/qiskit_convert_test.py
> release 0.49.0

- pytket/extensions/qiskit/backends/aer.py
- pytket/extensions/qiskit/backends/ibmq_emulator.py
- tests/backend_test.py
add support for contextual optimisation on local emulator
Solves https://github.com/CQCL/pytket-qiskit/issues/302
> add support for _contextual optimisation on local emulator

- pytket/extensions/qiskit/__init__.py
- pytket/extensions/qiskit/backends/__init__.py
- pytket/extensions/qiskit/backends/aer.py
- pytket/extensions/qiskit/backends/crosstalk_model.py
- pytket/extensions/qiskit/backends/ibm.py
- pytket/extensions/qiskit/backends/ibmq_emulator.py
- pytket/extensions/qiskit/qiskit_convert.py
- pytket/extensions/qiskit/result_convert.py
- pytket/extensions/qiskit/tket_backend.py
- pytket/extensions/qiskit/tket_job.py
- pytket/extensions/qiskit/tket_pass.py
- setup.py
- tests/backend_test.py
- tests/conftest.py
- tests/mock_pytket_backend.py
- tests/qiskit_backend_test.py
- tests/qiskit_convert_test.py
> update copyright notice

- .github/workflows/build_and_test.yml
- .github/workflows/issue-to-project.yml
- README.md
- _metadata.py
- docs/changelog.rst
- setup.py
> Release 0.55

- pytket/extensions/qiskit/qiskit_convert.py
- tests/qiskit_convert_test.py
> test changes

- _metadata.py
- docs/changelog.rst
- setup.py
> Release 0.57.0

- _metadata.py
- docs/changelog.rst
- setup.py
> Update dependencies, release 0.58.0

- .github/workflows/build_and_test.yml
Install the `.whl` file with pip inside the poetry env.
> fix: bad poetry install command in build and test workflow

- _metadata.py
- docs/changelog.md
- setup.py
> release 0.59.0

- docs/changelog.md
- pytket/extensions/qiskit/qiskit_convert.py
- tests/qiskit_convert_test.py
> release 0.62.0

- tests/qiskit_convert_test.py
> Remove a couple of deprecation warnings from the tests

- .github/workflows/build_and_test.yml
- README.md
- docs/changelog.md
- docs/index.md
- setup.py
> Add support for Python 3.13.

- .github/workflows/build_and_test.yml
Will change list of required checks after merging.
> Run on macos-latest.

- docs/index.md
> fix: correct link to RemoveBarriers documentation

- tests/mock_pytket_backend.py
> remove resultcache

- setup.py
> Require symengine.

- pytket/extensions/qiskit/backends/ibm.py
> Initialize `IBMQBackend._session` lazily.

- setup.py
> [revert me] set qiskit-ibm-runtime version to 0.41.1

- _metadata.py
- docs/changelog.md
- pytket/extensions/qiskit/backends/ibm.py
- pytket/extensions/qiskit/qiskit_convert.py
- setup.py
- tests/backend_test.py
Reverts https://github.com/CQCL/pytket-qiskit/pull/522
Reverts https://github.com/CQCL/pytket-qiskit/pull/518
Solves https://github.com/CQCL/pytket-qiskit/issues/521
Solves https://github.com/CQCL/pytket-qiskit/issues/519
Prepares for release 0.72.0
> Update to qiskit 2.2.0 and qiskit-ibm-runtime 0.42.0
