_metadata.py, docs/changelog.rst, pytket/extensions/qiskit/backends/ibm.py, pytket/extensions/qiskit/backends/ibmq_emulator.py, pytket/extensions/qiskit/tket_pass.py, setup.py, tests/backend_test.py, tests/conftest.py, tests/qiskit_backend_test.py, tests/qiskit_convert_test.py
Use the runtime service for both `IBMQBackend` and `IBMQEmulatorBackend`. For the latter, use the `ibmq_qasm_simulator` instead of the `AerBackend`.
Currently no error mitigation is applied. As an enhancement we could allow the user to pass options for this.
=> Use qiskit runtime for sampling in IBMQBackend.

docs/changelog.rst, pytket/extensions/qiskit/backends/aer.py
Bug reported by Iakov, who has also tested the fix. Problem is difference of endianness convention between pytket and qiskit.
=> Fix order of Pauli terms

docs/intro.txt
I've updated the documentation of `AerBackend` and added some highlighting for the different python classes in the index pages.
Let me know if you think more should be added. It might be nice to explain more about how `AerBackend` relates to the IBM simulator and maybe show how to define a `NoiseModel` or custom architecture.
=> update AerBackend docs and class highlighting

docs/changelog.rst, pytket/extensions/qiskit/qiskit_convert.py, tests/qiskit_convert_test.py
Relates to issue https://github.com/CQCL/pytket-qiskit/issues/100
Adding handling of qiskit circuits with `Initialize` and `StatePreparation` operations in the converters using the new `StatePreparationBox`
Previously users would have had to use `QuantumCircuit.decompose()` multiple times for this to work.
I've decided not to add logic for handling multiplexors as this would be more complicated and probably of limited value for the user.
[Initialize](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.initialize.html) inserts resets whereas [StatePreparation](https://qiskit.org/documentation/stubs/qiskit.circuit.library.StatePreparation.html) does not.
There are also several ways of constructing these (str, list, int) which I've tried to handle.
I have not added support …
=> handle state prep boxes in qiskit converters

docs/changelog.rst, pytket/extensions/qiskit/backends/ibm.py, setup.py, tests/backend_test.py, tests/conftest.py, tests/test-requirements.txt
Relates to the issue #112 
Newer IBM devices support the [ECR gate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.ECRGate.html) instead of the CX gate.
As a workaround I've defined a `RebaseCustom` to {X, SX, Rz, ECR} rather than defining a new decomposition for `auto_rebase_pass` in TKET itself
The CX replacement I've used is the following
* I've created a new `IBMBackend._primitive_gates` attribute which is either {X, SX, Rz, CX} , {X, SX, Rz, ECR} or the value returned by the `_tk_gateset` function depending on which gates get reported back from the API. I have also removed the `IBMQBackend._standard_gates` attribute.
* Prior to this PR we did a check if the Backend supported {X, SX, Rz, CX} in the default compilation. I've removed this as I wwant the rebase to be …
=> Support ECR gate in the gateset rebase and use pytest-rerunfailures

docs/changelog.rst, pytket/extensions/qiskit/qiskit_convert.py, tests/qiskit_convert_test.py
Adding the ability to handle the controlled gates mentioned in https://github.com/CQCL/pytket-qiskit/issues/88.
CCZ and CSX are both easily handled.
Also fixed the issue with Controlled gates not being handled correctly as `QControlBox`(es) in https://github.com/CQCL/pytket-qiskit/issues/134 .
=> Fix conversion of controllled gates

pytket/extensions/qiskit/backends/ibm.py
Redo of https://github.com/CQCL/pytket-qiskit/pull/160 without the accidental extra lines in the commit
Turns out `auto_rebase_pass{OpType.X, OpType.SX, OPType.Rz, OpType.ECR}` works just fine. Not sure how I missed this.
Given that it works we can remove some lines of code for the `RebaseCustom` workaround.
=> remove unecesaary RebaseCustom pass

pytket/extensions/qiskit/qiskit_convert.py, tests/qiskit_convert_test.py
Small PR to imporve the error message for failed `qiskit_to_tk` conversion adressing https://github.com/CQCL/pytket-qiskit/issues/150
This snippet now gives the following error message for the unsupported gate
```python
from qiskit import QuantumCircuit
from qiskit.circuit.library import XXPlusYYGate
from pytket.extensions.qiskit import qiskit_to_tk
qc = QuantumCircuit(2)
qc.append(XXPlusYYGate(0.1), [0, 1]) # add unsupported gate
tkc = qiskit_to_tk(qc)
```
Note: The two reverted commits correspond to an attempted fix of https://github.com/CQCL/pytket-qiskit/issues/43. However I realised this was slightly more involved than expected so its probably best adressed in a separate PR.
=> Improve error message for failed `qiskit_to_tk` conversion

docs/changelog.rst, pytket/extensions/qiskit/backends/aer.py, tests/backend_test.py
Fixes https://github.com/CQCL/pytket-qiskit/issues/186.
=> Support barriers in Aer simulators 

docs/changelog.rst, setup.py, tests/qiskit_backend_test.py, tests/qiskit_convert_test.py
Closes #19 .
There remains one warning (out of 229 initially), but this is coming from inside qiskit.
=> Eliminate deprecation warnings

.gitignore, pytket/extensions/qiskit/qiskit_convert.py, tests/qiskit_convert_test.py
Addresses #200 
Consider the following example
```python
import numpy as np
from qiskit import QuantumCircuit
from qiskit.circuit.library import RealAmplitudes
from pytket.extensions.qiskit import qiskit_to_tk
qc = QuantumCircuit(3)
params = [np.pi/2]*9
supply1 = RealAmplitudes(3, reps=2)
supply1 = supply1.assign_parameters(params)
qc.compose(supply1, qubits = [0, 1, 2], inplace=True)
```
If we try to convert `qc` to a pytket `Circuit` with `qiskit_to_tk` then we get 
```
RuntimeError: Gate has an invalid number of parameters
```
Now pytket-qiskit converts the instruction to a `CustomGate`. The actual gate definition works fine but the `Circuit.add_custom_gate()` method is failing because there are no free symbols in the circuit.
I've decided to just handle this case with `CircBox` as I …
=> Fix `RuntimeError` when converting qiskit instructions.

pytket/extensions/qiskit/backends/ibm.py
Summary: ci check on develop are not working, see for example https://github.com/CQCL/pytket-qiskit/actions/runs/6967703011/job/18968998699
I was not able to find the dynamic parameter in the qiskit documentation or changelog. It is unclear to my why this is not working.
I would assume that this parameter is not supported any more, but that is just guessing.
It is unclear to my, why this parameter was submitted to the backend again in the past, any helpful comments / opinions on this?
(We should also update https://cqcl.github.io/tket/pytket/api/predicates.html#pytket.predicates.NoFastFeedforwardPredicate it does not explain what this is used for)
=> remove unsupported dynamic parameter

pytket/extensions/qiskit/backends/ibm.py, tests/backend_test.py, tests/conftest.py, tests/mock_pytket_backend.py, tests/qiskit_convert_test.py
Some of the backends have been removed, updating the devices requires some changes.
=> update devices and tests

.github/workflows/build_and_test.yml, .github/workflows/docs.yml, README.md, docs/changelog.rst, docs/intro.txt, ecosystem.json, mypy.ini, setup.py
This PR drops python 3.9 support and adds python 3.12.
=> Update python support to 3.10, 3.11 and 3.12

.github/workflows/build_and_test.yml, .github/workflows/docs.yml, .github/workflows/docs/conf.py, README.md, _metadata.py, docs/changelog.rst, docs/intro.txt, ecosystem.json, mypy.ini, pytket/extensions/qiskit/__init__.py, pytket/extensions/qiskit/backends/__init__.py, pytket/extensions/qiskit/backends/aer.py, pytket/extensions/qiskit/backends/crosstalk_model.py, pytket/extensions/qiskit/backends/ibm.py, pytket/extensions/qiskit/backends/ibmq_emulator.py, pytket/extensions/qiskit/qiskit_convert.py, pytket/extensions/qiskit/result_convert.py, pytket/extensions/qiskit/tket_backend.py, pytket/extensions/qiskit/tket_job.py, pytket/extensions/qiskit/tket_pass.py, setup.py, tests/backend_test.py, tests/conftest.py, tests/mock_pytket_backend.py, tests/qiskit_backend_test.py, tests/qiskit_convert_test.py
=> Release 0.48.0

docs/changelog.rst, pytket/extensions/qiskit/backends/ibmq_emulator.py
Without this the default `ibm-q/open/main` instance is used for the `ibmq_qasm_simulator` backend.
=> Pass `instance` to `QiskitRuntimeService`

docs/intro.txt
Closes #261 
Fixes the links in the "Backends available through pytket-qiskit" section of the docs. Probably a copy/paste error.
=> Fix `Backend` links in API docs

pytket/extensions/qiskit/backends/ibm.py
IBMQBackend._session is supplied the `instance` argument from IBMQBackend constructor. This is important when using the default or reserved instances of IBMQ access.
- [yes] I have performed a self-review of my code.
- [yes] I have commented hard-to-understand parts of my code.
- [no] I have made corresponding changes to the public API documentation.
- [no] I have added tests that prove my fix is effective or that my feature works.
- [no] I have updated the changelog with any user-facing changes.
=> qiskit session is supplied the instance from IBMQBackend constructor

docs/api.rst, docs/changelog.rst, docs/intro.txt, pytket/extensions/qiskit/__init__.py, pytket/extensions/qiskit/backends/__init__.py, pytket/extensions/qiskit/backends/ibmq_emulator.py, pytket/extensions/qiskit/backends/ibmq_local_emulator.py, tests/backend_test.py, tests/conftest.py
Add a new backend `IBMQLocalEmulatorBackend` which uses `AerBackend` with the noise model and characteristics of the real device. This is similar to `IBMQEmulatorBackend` except that it does all emulation locally. The only outward difference is that it does not support contextual optimization (because `AerBackend` doesn't).
Closes #65 .
=> Add local emulator backend

docs/changelog.rst, docs/intro.txt, pytket/extensions/qiskit/backends/aer.py, pytket/extensions/qiskit/backends/crosstalk_model.py, pytket/extensions/qiskit/backends/ibmq_emulator.py, pytket/extensions/qiskit/backends/ibmq_local_emulator.py, pytket/extensions/qiskit/qiskit_convert.py, pytket/extensions/qiskit/tket_pass.py, setup.py, tests/backend_test.py, tests/qiskit_backend_test.py, tests/qiskit_convert_test.py
This PR makes the minimal changes needed to get the tests working with Qiskit 1.0. It's possible this is all that's needed for full compatibility, but I'm not familiar with the repo so am just relying on getting the tests passing.
Most changes are just find/replace, the only exception being a tweak to `add_qiskit_data` to handle some removed attributes of `Clbit`.
Closes #263 .
=> Update for Qiskit 1.0

docs/intro.txt
Updated the docs on saving IBM credentials. I think we can safely remove the notes about using pytket-qiskit v0.39 or older at this point.
I've also explicitly separted the two methods for saving credentials. Hopefully this avoids some confusion.
Closes #275
=> Improve docs on saving IBM credentials

setup.py
Update the version of `qiskit-algorithms` to 0.3.0 as it's the first version that supports `qiskit` 1.0. https://qiskit-community.github.io/qiskit-algorithms/release_notes.html#release-notes-0-3-0
=> Bump qiskit-algorithms dep to 0.3.0

tests/qiskit_convert_test.py
Adding tests for https://github.com/CQCL/pytket-qiskit/pull/314 
=> add testcase for symbolic conversion

docs/changelog.rst, pytket/extensions/qiskit/backends/ibm.py, tests/backend_test.py
Fixing https://github.com/CQCL/pytket-qiskit/issues/312
=> fix directed ECR gate

docs/changelog.rst, docs/intro.txt, pytket/extensions/qiskit/backends/ibm.py, pytket/extensions/qiskit/backends/ibmq_emulator.py, pytket/extensions/qiskit/qiskit_convert.py, pytket/extensions/qiskit/tket_backend.py, pytket/extensions/qiskit/tket_pass.py, setup.py, tests/backend_test.py, tests/conftest.py, tests/qiskit_backend_test.py
All the functionality from `IBMProvider` is now provided by `QiskitRuntimeService`.
Closes #325 .
=> Use QiskitRuntimeService instead of IBMProvider

docs/changelog.rst, pytket/extensions/qiskit/backends/ibm.py, tests/backend_test.py, tests/conftest.py, tests/qiskit_backend_test.py, tests/qiskit_convert_test.py, tests/test-requirements.txt
The main change is to migrate from `SamplerV1` to `SamplerV2`. One implication is replacing the `options` parameter to `IBMQBackend.process_circuits()` with a `sampler_options` parameter (of a different type).
Also significant is removal of support for the "ibmq_qasm_simulator" backend, which is due to be retired on 15 May 2024.
I haven't done the migration from `BackendV1` to `BackendV2` because `BackendV1` is not (yet) deprecated.
Fixed and re-enabled one test.
Closes #19 .
=> Eliminate all warnings from tests

docs/changelog.rst, pytket/extensions/qiskit/qiskit_convert.py, tests/qiskit_convert_test.py
Qiskit circuits can only contain qubits and bits that are singly indexed in a contiguous manner starting from 0. Currently we just create registers large enough to contain the highest index in the pytket circuit. This is OK for qubits but for bits it causes incorrect results. The simplest fix is just to disallow this (rare) case.
Fixes #337 .
=> Forbid circuits with incomplete classical registers in tk_to_qiskit()

pytket/extensions/qiskit/backends/ibm.py
We were assuming a `SamplerResult`. We still handle that case, though I don't know if it ever occurs.
This PR supersedes #335 .
Fixes #334 .
=> Handle PrimitiveResult as result type

docs/changelog.rst, pytket/extensions/qiskit/backends/__init__.py, pytket/extensions/qiskit/backends/aer.py, tests/qiskit_convert_test.py
When both qiskit-aer and qiskit-aer-gpu are installed, there are two Aer backend with the name "aer_simulator".
Tested locally with and without the qiskit-aer-gpu package.
Fixes #352 .
=> Don't error if more than one "aer_simulator" backend is available

pytket/extensions/qiskit/backends/ibm.py
`status` has no attribute `name` for IBMQ QPUs (e.g. ibm_brisbane) such that an `AttributeError` occurs when executing on e.g. ibm_brisbane. 
_Note:_  This is not a problem for the AerSimulator, such that the tests are still working.
=> Update ibm.py to enable execution on IBM QPUs

docs/changelog.rst, mypy.ini, pytket/extensions/qiskit/qiskit_convert.py, setup.py, tests/qiskit_convert_test.py
=> update mypy and pytket

docs/changelog.rst, pytket/extensions/qiskit/qiskit_convert.py, setup.py
Fix the conversion of symbols from pytket circuits to qiskit so that round-trip equality checks pass.
This needs qiskit >= 1.2.0 to work, so bump the minimum qiskit version.
Fixes #376 .
=> Fix symbol conversion into qiskit

docs/changelog.rst, pytket/extensions/qiskit/qiskit_convert.py, tests/qiskit_convert_test.py
Add support for converting controlled unitary gates from Qiskit to TKET.
I have yet to update the changelog/API docs, in case more changes or refactoring are required.
=> Add conversion of controlled unitary gates from Qiskit to TKET.

pytket/extensions/qiskit/backends/aer.py, pytket/extensions/qiskit/backends/ibm.py, pytket/extensions/qiskit/qiskit_convert.py, tests/qiskit_convert_test.py
These are the low-hanging fruit. The main change still to come is migration from `BackendV1` to `BackendV2`.
=> Get rid of some deprecation warnings

.github/workflows/docs/conf.py, docs/intro.txt, pytket/extensions/qiskit/backends/aer.py, pytket/extensions/qiskit/backends/config.py, pytket/extensions/qiskit/backends/crosstalk_model.py, pytket/extensions/qiskit/backends/ibm.py, pytket/extensions/qiskit/backends/ibm_utils.py, pytket/extensions/qiskit/backends/ibmq_emulator.py, pytket/extensions/qiskit/qiskit_convert.py, pytket/extensions/qiskit/result_convert.py, pytket/extensions/qiskit/tket_backend.py, pytket/extensions/qiskit/tket_job.py, pytket/extensions/qiskit/tket_pass.py, tests/backend_test.py, tests/mock_pytket_backend.py, tests/qiskit_convert_test.py
Used python 3.10+ types everywhere now that only 3.10+ versions of python are supported.
Some examples
* use `|` rather than `Union`
* using `list` rather than `typing.List`. `dict` rather than `typing.Dict` etc.
If we want to do this for other repos we can use [pyupgrade](https://github.com/asottile/pyupgrade) to automate most of this.
Also removed some redundant type declarations for sphinx e.g. `:type` and `:rtype`. the [sphinx-autodoc-typehints](https://github.com/tox-dev/sphinx-autodoc-typehints) extension infers the types from the function signature so we can remove a little duplication.
Not very important to do this but it was quick and easy to do.
Also cleaned up [this docs page](https://tket.quantinuum.com/extensions/pytket-qiskit/) a bit. Making more use of sphinx …
=> chore: use python 3.10+ types, cleanup docs

docs/api.rst, docs/changelog.rst, docs/intro.txt, pytket/extensions/qiskit/__init__.py, pytket/extensions/qiskit/backends/__init__.py, pytket/extensions/qiskit/backends/aer.py, pytket/extensions/qiskit/result_convert.py, tests/backend_test.py
Adding a new `AerDensityMatrixBackend` class. Unlike other density matrix simulators available through the pytket extensions this emulator should support an optional `NoiseModel` in the constructor.
There's a decent amount of duplication from the `AerBackend` implementation for `BackendInfo`. Maybe there's a smarter and less error prone way to do it. 
closes #231
=> feat: add density matrix simulation via qiskit Aer

pytket/extensions/qiskit/backends/ibm.py, pytket/extensions/qiskit/qiskit_convert.py, setup.py, tests/qiskit_backend_test.py, tests/test-requirements.txt
Another step towards #350 ...
I think the only deprecation warnings now are from `TketBackend`, which is not so easy to update and may require a complete rewrite ...
I deleted a couple of tests that use `qiskit_algorithms` which depended on the deprecated classes. There is a similar example in the user manual. I've checked that it still works.
=> Remove some deprecation warnings

pytket/extensions/qiskit/qiskit_convert.py
Replaces the rebase pass in the `tk_to_qiskit` conversion with `AutoRebase`. It doesn't require a `tk1_replacement` function and so it better from the point of view of serialization. Its also a bit cleaner syntatically and allows us to delete some unecessary lines which define variables for `RebaseCustom`.
This PR supercedes #386 as I don't see a reason for this to wait until the refactor of `tk_to_qiskit` and `qiskit_to_tk` is done.
As mentioned in the related issue, I'm a little puzzled that this shows up in the dict of the `default_compilation_pass` for IBM backends. I think it would be worth checking to see if the passes are serilaized correctly.
#361
=> Use `AutoRebase` in `tk_to_qiskit` rather than `RebaseCustom`

docs/changelog.rst, pytket/extensions/qiskit/tket_pass.py
Last of the low-hanging fruit? Just `TketBackend` to go.
=> Initialize `TketAutoPass` with a `BackendV2`

pytket/extensions/qiskit/qiskit_convert.py
This PR begins a refactor of the `qiskit_to_tk` and `tk_to_qiskit` converters. Here I've focussed on refactoring some of the large `CircuitBuilder.add_qiskit_data` method (used as part of `qiskit_to_tk` into separate internal functions. I've added some short docstrings so its hopefully clearer whats going on.
There's still a lot to improve in the conversion code but I think it makes sense to do this refactor in several stages to make small fixes like https://github.com/CQCL/pytket-qiskit/issues/366 a bit easier.
I've avoided imporvements which involve user facing changes for now. Will add these in a follow up.
#313
=> refactor: Simplify some internals of `qiskit_to_tk` conversion

docs/changelog.rst, pytket/extensions/qiskit/tket_backend.py, pytket/extensions/qiskit/tket_job.py
Closes #350 .
This change would break [one of the examples](https://docs.quantinuum.com/tket/user-guide/manual/manual_backend.html#embedding-into-qiskit) in the manual, and perhaps also one or two places in the example notebooks (I haven't checked). This shouldn't affect the docs build since it's pinned to a specific version of pytket-qiskit, but we should probably revise those sections. It seems that the relevant parts of `qiskit_algorithms` (a community-maintained project) haven't yet been updated to use the new backend class.
This PR removes the last of the deprecation warnings from the qiskit tests that were coming from our code.
=> Update `TketBackend` to derive from `BackendV2`

docs/changelog.rst, pytket/extensions/qiskit/qiskit_convert.py, tests/backend_test.py, tests/qiskit_convert_test.py
Replace CnY and CnZ in qiskit gates
https://github.com/CQCL/pytket-qiskit/commit/519a5123e4c0a4ff93c7077b3cb2f827522ebe87?diff=split&w=1
Make a test function
https://github.com/CQCL/pytket-qiskit/commit/94128565c8edfa5a8fd461459f315932f4299cb9?diff=split&w=0
https://github.com/CQCL/pytket-qiskit/issues/368
=> fix: Allow circuits containing CnZ gates to run on `AerBackend`

docs/intro.txt
fixing the alignment of this table for `TketBackend` and related classes.
Before 
After below (Ignore the styling difference. The latter was built locally using the legacy theme. In the website build the new theme will be used. After #392 we will be able to do local builds with the latest version of the theme)
Also fixed an inconsistent variable in [6d231fe](https://github.com/CQCL/pytket-qiskit/pull/393/commits/6d231fe9c60d2e73200d7d29c37e1c5b39730d47)
=> docs: fix autosummary table alignment on docs page

.github/workflows/build_and_test.yml, docs/changelog.rst, pytket/extensions/qiskit/qiskit_convert.py, tests/qiskit_convert_test.py
This PR adds support for handling the `control_state` of a controlled operation in the `qiskit_to_tk` and `tk_to_qiskit` converters. The control state is now handled directly instead of adding `X` gates on the control qubits.
I've also taken the liberty of refactoring out the "`QControlBox` building" from the `CircuitBuildier.add_qiskit_data` method in the same spirit as  #382 
I've also reworked some internals of how unitary gates are converted to and fro. Handling of controlled unitary boxes was added in #372 . ~I think it'd be fairly easy to add the other direction into this PR too (see #378)~ (I think its best to do this separately).
Original PR adding control state handling with X gates -> https://github.com/CQCL/pytket-qiskit/pull/118
#378 
#313 
closes #178
=> feat: Improved handling of controlled gates in converters

docs/index.rst
Minor update to the docs inlcuding mentioning the gatesets explicitly and linking to the docs for `AutoRebase`.
=> docs: update docs on supported gatesets

.github/workflows/build_and_test.yml, .github/workflows/docs.yml, .github/workflows/lint.yml
The `macos-12` runner is being removed soon; `macos-latest` is currently `macos-14`. Also update to `ubuntu-24.04` a.k.a. `ubuntu-latest` while we're here.
(Will update names of "required checks" after approval.)
=> Update runners used on CI

pytket/extensions/qiskit/backends/aer.py, pytket/extensions/qiskit/result_convert.py, tests/qiskit_convert_test.py
Adds parameters to `qiskit_result_to_backendresult` / `qiskit_experimentresult_to_backendresult` to specify which type of results we expect to have back.
Previously, circuits with classical bits submitted to AerStateBackend would have a `counts` field in their returned result, because Qiskit reads from the classical register memory. Now we don't set that, because we don't expect counts to be returned from AerStateBackend so we ignore that field.
Also, we weren't ever passing in anything to `ppcirc` in `qiskit_experimentresult_to_backendresult`, so after discussion with @cqc-melf and @cqc-alec  that's been removed as part of this PR.
=> Specify what result types we expect in our Qiskit result conversion functions

docs/changelog.rst, pytket/extensions/qiskit/backends/ibm.py
Fixes #339 .
Also use `PrimitiveResult` for debug results instead of `SamplerResult`, to match real devices.
Tested locally by running:
```python
from pytket.circuit import Circuit, Qubit, Bit
from pytket.extensions.qiskit import IBMQBackend
b = IBMQBackend("ibm_nazca")
c = Circuit(5)
c.add_c_register("a", 2)
c.add_c_register("b", 2)
c.add_c_register("c", 1)
c.H(0).CX(0, 1).Measure(Qubit(3), Bit("b", 1)).Measure(Qubit(0), Bit("c", 0))
c1 = b.get_compiled_circuit(c, optimisation_level=1)
h = b.process_circuit(c1, n_shots=10)
r = b.get_result(h)
print(r.get_counts(cbits=[Bit("b", 1), Bit("c", 0)]))
```
Output:
```
Counter({(0, 0): 6, (0, 1): 4})
```
=> Handle bits selection in results for circuits with non-default registers

docs/changelog.md, pytket/extensions/qiskit/qiskit_convert.py, tests/qiskit_convert_test.py
Minor change to `tk_to_qiskit`. The user now gets a warning if the input pytket `Circuit` contains implicit qubit permutations.
closes #411 
#411
=> fix: Warn user about implicit qubit permutations in `tk_to_qiskit`

docs/changelog.md, docs/index.md, pytket/extensions/qiskit/qiskit_convert.py, tests/qiskit_convert_test.py
reverts #412 
See explanation here -> https://github.com/CQCL/pytket-qiskit/issues/411#issuecomment-2488799379
Drive by: Clarify how the default pass works in the docs for `AerBackend` when no `NoiseModel` is used.
#411
=> Revert warning related to implcit swaps

docs/changelog.md, docs/index.md, pytket/extensions/qiskit/backends/aer.py, pytket/extensions/qiskit/backends/ibm.py, pytket/extensions/qiskit/backends/ibm_utils.py, setup.py, tests/backend_test.py
Add a new optimisation level to `pytket-qiskit` that uses `GreedyPauliSimp` to optimise circuits.
=> Add optimisation level 3 

docs/changelog.md, pytket/extensions/qiskit/backends/aer.py, tests/backend_test.py
Fixes #420 .
Regression was introduced in pytket-qiskit 0.51.0.
=> Fix `get_results()` when `process_circuits()` given circuits of different sizes

docs/changelog.md, docs/index.md, pytket/extensions/qiskit/backends/aer.py, pytket/extensions/qiskit/qiskit_convert.py, tests/qiskit_convert_test.py
Added the change from #412 back in again with a boolean flag to ensure that unhelpful warnings aren't generated when using `AerBackend` with optimisation level 2
See discusssion in #411 
Driveby: fix invalid table of compilation passes (see [df0cda3](https://github.com/CQCL/pytket-qiskit/pull/421/commits/df0cda3d1c46d8cbe5d69c9e9f43990cdd846bc7))
closes #411
=> fix: improve implicit qubit permutations warning

docs/index.md
These should no longer be necessary after this prefix is removed from the docs
see https://github.com/CQCL/tket/issues/1719
=> docs: replace `_tket` links

tests/backend_test.py
Fixes #428 .
Must have been a change in the Aer unitary simulator causing the global phase computation to change.
=> Compare unitaries up to global phase.

docs/changelog.md, setup.py, tests/qiskit_convert_test.py
We need to update to qiskit 1.3.1 in order to use it.
Closes #429 .
Closes #431 .
=> Use `MCMTGate` instead of deprecated `MCMT`

docs/changelog.md, pytket/extensions/qiskit/qiskit_convert.py, tests/qiskit_convert_test.py
=> Keep list of bits storing range predicates up to date when converting

pytket/extensions/qiskit/backends/aer.py, pytket/extensions/qiskit/backends/ibm.py
=> fix: typos in Aer and IBM docstrings

docs/changelog.md, pytket/extensions/qiskit/qiskit_convert.py, tests/qiskit_convert_test.py
See #442 .
It would be good to support this, but better to raise an error than to convert incorrectly.
=> Raise error when converting nested conditionals

docs/changelog.md, pytket/extensions/qiskit/backends/ibm.py, pytket/extensions/qiskit/backends/ibmq_emulator.py
Closes #413 .
The test failure is unrelated: see #449 .
It is not currently possible to add a CI test for this as none of the devices on the open plan support fractional gates. But I have tested locally with `ibm_torino`.
In addition, I have added a squashing step to the default compilation passes, since they were not squashing single-qubit gates (as pointed out in the comments on the issue).
=> Add support for "fractional gates"

setup.py
This relaxes the condition in line with the general policy of having upper bounds only when known to be necessary. The upper bound of 2 _is_ needed bacause qiskit 2 will remove some things like `Instruction.c_if()` that we depend on, and we can't yet remove that dependence because of limitations in current qiskit. (I've made a [qiskit-2 branch](https://github.com/CQCL/pytket-qiskit/tree/ae/qiskit-2) which we can hopefully merge after the release of qiskit 2.)
=> Allow versions of qiskit >= 1.3.1 but < 2.

docs/build-docs.sh, docs/index.md, pytket/extensions/qiskit/qiskit_convert.py
1.  Picking up the docs link fix from https://github.com/CQCL/pytket-qiskit/pull/443 so we don't have to wait for the docs build in C.I. to be fixed.
2. Update docs theming submodule
3. update the docs build script to replace all `_tket` links for the passes in the default compilation table
Only (1.) affects the website. Everything else is just for the docs build in pytket-qiskit. This is still broken. See #458 
Drive by: black format the `qiskit_convert.py` file after a `black` package update.
closes #444
=> docs: fix link for `RemoveBarriers` pass, update docs build scripts

pytket/extensions/qiskit/backends/aer.py, pytket/extensions/qiskit/backends/ibm.py, pytket/extensions/qiskit/qiskit_convert.py, setup.py, tests/backend_test.py, tests/mock_pytket_backend.py
`PulseBackendConfiguration` has been [removed](https://github.com/Qiskit/qiskit-ibm-runtime/pull/2180) in qiskit runtime 0.37.0, all backends now return `QasmBackendConfiguration`. This PR also includes the necessary changes to comply with the new ruff rules.
=> Update to qiskit ibm runtime 0.37.0

docs/changelog.md
Just fixing the markdown heading
This is how it looks in the deployed docs before this change.
=> fix: update changelog heading

docs/changelog.md, pytket/extensions/qiskit/backends/aer.py, tests/backend_test.py
=> Don't introduce implicit swaps when transpiling for unitary and density-matrix backends

.github/workflows/build_and_test.yml
They can fail because of timeouts and network issues which we don't want to block a release. They should already have been run in PRs for every change anyway.
=> Don't run remote checks in release workflow.
